package wrapper

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kawaz/shimux/internal/ghostty/ghosttytest"
	"github.com/kawaz/shimux/internal/pane"
)

// --- GenerateSessionName ---

func TestGenerateSessionName_AlphaNumericAndDash(t *testing.T) {
	got := GenerateSessionName("my-session-01")
	want := "my-session-01"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "my-session-01", got, want)
	}
}

func TestGenerateSessionName_SpecialChars(t *testing.T) {
	got := GenerateSessionName("my session/foo.bar:baz")
	want := "my_session_foo_bar_baz"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "my session/foo.bar:baz", got, want)
	}
}

func TestGenerateSessionName_Empty(t *testing.T) {
	got := GenerateSessionName("")
	want := ""
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "", got, want)
	}
}

func TestGenerateSessionName_AllSpecial(t *testing.T) {
	got := GenerateSessionName("@#$%")
	want := "____"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "@#$%", got, want)
	}
}

// --- replaceEnv ---

func TestReplaceEnv_ExistingKey(t *testing.T) {
	env := []string{"HOME=/home/user", "PATH=/usr/bin", "SHELL=/bin/bash"}
	result := replaceEnv(env, "PATH", "PATH=/new/path")
	found := false
	for _, e := range result {
		if e == "PATH=/new/path" {
			found = true
		}
		if e == "PATH=/usr/bin" {
			t.Error("old PATH value should have been replaced")
		}
	}
	if !found {
		t.Error("PATH=/new/path not found in result")
	}
	if len(result) != 3 {
		t.Errorf("expected len=3, got %d", len(result))
	}
}

func TestReplaceEnv_NewKey(t *testing.T) {
	env := []string{"HOME=/home/user"}
	result := replaceEnv(env, "SHIMUX", "SHIMUX=1")
	if len(result) != 2 {
		t.Errorf("expected len=2, got %d", len(result))
	}
	if result[1] != "SHIMUX=1" {
		t.Errorf("expected appended SHIMUX=1, got %q", result[1])
	}
}

// --- New ---

func TestNew_WithAllConfig(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test-session",
		ShimuxPath:    "/usr/local/bin/shimux",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if w.session != "test-session" {
		t.Errorf("session = %q, want %q", w.session, "test-session")
	}
	if w.shimuxPath != "/usr/local/bin/shimux" {
		t.Errorf("shimuxPath = %q, want %q", w.shimuxPath, "/usr/local/bin/shimux")
	}
}

func TestNew_EmptySession_AutoGenerated(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		ShimuxPath:    "/usr/local/bin/shimux",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if w.session == "" {
		t.Error("session should be auto-generated when empty")
	}
}

func TestNew_EmptyShimuxPath_UsesExecutable(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if w.shimuxPath == "" {
		t.Error("shimuxPath should be set via os.Executable() when empty")
	}
}

func TestNew_NilController_Error(t *testing.T) {
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	_, err := New(Config{
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/usr/local/bin/shimux",
	})
	if err == nil {
		t.Fatal("New() with nil Controller should return error")
	}
	if !strings.Contains(err.Error(), "controller is required") {
		t.Errorf("error = %q, want to contain 'controller is required'", err.Error())
	}
}

func TestNew_NilPaneManager_Error(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	_, err := New(Config{
		Controller: ctrl,
		Session:    "test",
		ShimuxPath:   "/usr/local/bin/shimux",
	})
	if err == nil {
		t.Fatal("New() with nil PaneManager should return error")
	}
	if !strings.Contains(err.Error(), "pane manager is required") {
		t.Errorf("error = %q, want to contain 'pane manager is required'", err.Error())
	}
}

func TestNew_SessionNameSanitized(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "my session/foo",
		ShimuxPath:    "/usr/local/bin/shimux",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	want := "my_session_foo"
	if w.session != want {
		t.Errorf("session = %q, want %q", w.session, want)
	}
}

// --- Setup ---

func TestSetup_CreatesTmpDirAndSymlink(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo", // 実在するバイナリのパス
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	// 一時ディレクトリが存在する
	if _, err := os.Stat(w.tmpDir); os.IsNotExist(err) {
		t.Errorf("tmpDir %q does not exist", w.tmpDir)
	}

	// tmux シンボリックリンクが存在する
	symlinkPath := filepath.Join(w.tmpDir, "tmux")
	target, err := os.Readlink(symlinkPath)
	if err != nil {
		t.Fatalf("Readlink(%q) error = %v", symlinkPath, err)
	}
	if target != "/bin/echo" {
		t.Errorf("symlink target = %q, want %q", target, "/bin/echo")
	}
}

// --- Env ---

func TestEnv_ContainsRequiredVars(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test-session",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	envVars := w.Env()
	envMap := make(map[string]string)
	for _, e := range envVars {
		parts := strings.SplitN(e, "=", 2)
		if len(parts) == 2 {
			envMap[parts[0]] = parts[1]
		}
	}

	// PATH starts with tmpDir
	pathVal, ok := envMap["PATH"]
	if !ok {
		t.Fatal("PATH not found in Env()")
	}
	if !strings.HasPrefix(pathVal, w.tmpDir+":") {
		t.Errorf("PATH should start with %q, got %q", w.tmpDir+":", pathVal)
	}

	// TMUX
	tmuxVal, ok := envMap["TMUX"]
	if !ok {
		t.Fatal("TMUX not found in Env()")
	}
	expectedTMUX := fmt.Sprintf("%s/shimux,%d,0", w.tmpDir, os.Getpid())
	if tmuxVal != expectedTMUX {
		t.Errorf("TMUX = %q, want %q", tmuxVal, expectedTMUX)
	}

	// SHIMUX
	if envMap["SHIMUX"] != "1" {
		t.Errorf("SHIMUX = %q, want %q", envMap["SHIMUX"], "1")
	}

	// SHIMUX_SESSION
	if envMap["SHIMUX_SESSION"] != "test-session" {
		t.Errorf("SHIMUX_SESSION = %q, want %q", envMap["SHIMUX_SESSION"], "test-session")
	}

	// SHIMUX_PANE_ID
	if envMap["SHIMUX_PANE_ID"] != "0" {
		t.Errorf("SHIMUX_PANE_ID = %q, want %q", envMap["SHIMUX_PANE_ID"], "0")
	}

	// TMUX_PANE
	if envMap["TMUX_PANE"] != "%0" {
		t.Errorf("TMUX_PANE = %q, want %q", envMap["TMUX_PANE"], "%0")
	}
}

// --- Cleanup ---

func TestCleanup_RemovesTmpDir(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}

	tmpDir := w.tmpDir
	if err := w.Cleanup(); err != nil {
		t.Fatalf("Cleanup() error = %v", err)
	}

	if _, err := os.Stat(tmpDir); !os.IsNotExist(err) {
		t.Errorf("tmpDir %q should have been removed", tmpDir)
	}
}

func TestCleanup_NoTmpDir_NoError(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	// Setup() を呼ばずにCleanup()
	if err := w.Cleanup(); err != nil {
		t.Fatalf("Cleanup() without Setup() should not error, got %v", err)
	}
}

// --- Run ---

func TestRun_NoArgs_Error(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), nil)
	if err == nil {
		t.Fatal("Run() with no args should return error")
	}
	if !strings.Contains(err.Error(), "no command specified") {
		t.Errorf("error = %q, want to contain 'no command specified'", err.Error())
	}
}

func TestRun_EmptyArgs_Error(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{})
	if err == nil {
		t.Fatal("Run() with empty args should return error")
	}
}

func TestRun_TrueCommand_Success(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"true"})
	if err != nil {
		t.Fatalf("Run('true') error = %v", err)
	}

	// Cleanup が呼ばれて一時ディレクトリが削除されている
	if w.tmpDir != "" {
		if _, err := os.Stat(w.tmpDir); !os.IsNotExist(err) {
			t.Errorf("tmpDir should have been cleaned up after Run()")
		}
	}
}

func TestRun_EchoCommand_Success(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"echo", "hello"})
	if err != nil {
		t.Fatalf("Run('echo', 'hello') error = %v", err)
	}
}

func TestRun_FalseCommand_ReturnsError(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"false"})
	if err == nil {
		t.Fatal("Run('false') should return error")
	}
}

func TestRun_RegistersInitialPane(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"true"})
	if err != nil {
		t.Fatalf("Run('true') error = %v", err)
	}

	// ペインが1つ登録されている
	panes := pm.List()
	if len(panes) != 1 {
		t.Fatalf("expected 1 pane registered, got %d", len(panes))
	}
	if panes[0].ID != "0" {
		t.Errorf("first pane ID = %q, want %q", panes[0].ID, "0")
	}
}

func TestRun_ContextCancel(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // 即キャンセル

	err = w.Run(ctx, []string{"sleep", "10"})
	if err == nil {
		t.Fatal("Run() with cancelled context should return error")
	}
}

// --- replaceEnv edge cases ---

func TestReplaceEnv_EmptySlice(t *testing.T) {
	result := replaceEnv(nil, "KEY", "KEY=value")
	if len(result) != 1 {
		t.Fatalf("expected len=1, got %d", len(result))
	}
	if result[0] != "KEY=value" {
		t.Errorf("expected %q, got %q", "KEY=value", result[0])
	}
}

func TestReplaceEnv_KeyWithEqualsInValue(t *testing.T) {
	env := []string{"FOO=bar=baz"}
	result := replaceEnv(env, "FOO", "FOO=new=val")
	if len(result) != 1 {
		t.Fatalf("expected len=1, got %d", len(result))
	}
	if result[0] != "FOO=new=val" {
		t.Errorf("expected %q, got %q", "FOO=new=val", result[0])
	}
}

func TestReplaceEnv_MultipleKeys_OnlyTargetReplaced(t *testing.T) {
	env := []string{"A=1", "B=2", "C=3"}
	result := replaceEnv(env, "B", "B=99")
	if len(result) != 3 {
		t.Fatalf("expected len=3, got %d", len(result))
	}
	if result[0] != "A=1" || result[1] != "B=99" || result[2] != "C=3" {
		t.Errorf("unexpected result: %v", result)
	}
}

// --- Setup edge cases ---

func TestSetup_SymlinkTargetResolvesToShimuxPath(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	// /usr/bin/true は macOS に存在する実在バイナリ
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/usr/bin/true",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	symlinkPath := filepath.Join(w.tmpDir, "tmux")
	target, err := os.Readlink(symlinkPath)
	if err != nil {
		t.Fatalf("Readlink error = %v", err)
	}
	if target != "/usr/bin/true" {
		t.Errorf("symlink target = %q, want %q", target, "/usr/bin/true")
	}
}

func TestSetup_TmuxSymlinkIsExecutable(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	// symlink 先の /bin/echo が実行可能であることを確認
	symlinkPath := filepath.Join(w.tmpDir, "tmux")
	info, err := os.Stat(symlinkPath) // Stat は symlink を辿る
	if err != nil {
		t.Fatalf("Stat error = %v", err)
	}
	if info.Mode()&0111 == 0 {
		t.Error("tmux symlink target should be executable")
	}
}

// --- Env edge cases ---

func TestEnv_PathPrependedBeforeOriginal(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	envVars := w.Env()
	for _, e := range envVars {
		if strings.HasPrefix(e, "PATH=") {
			pathVal := strings.TrimPrefix(e, "PATH=")
			parts := strings.SplitN(pathVal, ":", 2)
			if parts[0] != w.tmpDir {
				t.Errorf("PATH first component = %q, want %q", parts[0], w.tmpDir)
			}
			if len(parts) < 2 || parts[1] == "" {
				t.Error("PATH should contain original PATH after tmpDir")
			}
			return
		}
	}
	t.Fatal("PATH not found in Env()")
}

func TestEnv_TMUXContainsShimuxSocketPath(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}
	defer w.Cleanup()

	envVars := w.Env()
	for _, e := range envVars {
		if strings.HasPrefix(e, "TMUX=") {
			tmuxVal := strings.TrimPrefix(e, "TMUX=")
			if !strings.Contains(tmuxVal, "/shimux,") {
				t.Errorf("TMUX = %q, should contain '/shimux,'", tmuxVal)
			}
			// TMUX 形式: socket_path,pid,window_index
			parts := strings.Split(tmuxVal, ",")
			if len(parts) != 3 {
				t.Errorf("TMUX = %q, expected 3 comma-separated parts", tmuxVal)
			}
			return
		}
	}
	t.Fatal("TMUX not found in Env()")
}

func TestEnv_BeforeSetup_PathStartsEmpty(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	// Setup() を呼ばずに Env() → tmpDir が空なのでPATH先頭は ":"
	envVars := w.Env()
	for _, e := range envVars {
		if strings.HasPrefix(e, "PATH=") {
			pathVal := strings.TrimPrefix(e, "PATH=")
			if !strings.HasPrefix(pathVal, ":") {
				t.Errorf("before Setup(), PATH should start with ':' (empty tmpDir), got %q", pathVal)
			}
			return
		}
	}
	t.Fatal("PATH not found in Env()")
}

// --- Cleanup edge cases ---

func TestCleanup_IdempotentMultipleCalls(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}

	tmpDir := w.tmpDir

	// 1回目: 正常削除
	if err := w.Cleanup(); err != nil {
		t.Fatalf("Cleanup() first call error = %v", err)
	}
	if _, err := os.Stat(tmpDir); !os.IsNotExist(err) {
		t.Errorf("tmpDir should be removed after first Cleanup()")
	}

	// 2回目: ディレクトリは既に無いが、tmpDir フィールドは残っている
	// os.RemoveAll は存在しないパスでもエラーにならない
	if err := w.Cleanup(); err != nil {
		t.Fatalf("Cleanup() second call should not error, got %v", err)
	}
}

func TestCleanup_SymlinkAlsoRemoved(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if err := w.Setup(); err != nil {
		t.Fatalf("Setup() error = %v", err)
	}

	symlinkPath := filepath.Join(w.tmpDir, "tmux")

	// symlink が存在する
	if _, err := os.Lstat(symlinkPath); os.IsNotExist(err) {
		t.Fatal("symlink should exist before Cleanup()")
	}

	if err := w.Cleanup(); err != nil {
		t.Fatalf("Cleanup() error = %v", err)
	}

	// symlink も消えている
	if _, err := os.Lstat(symlinkPath); !os.IsNotExist(err) {
		t.Error("symlink should be removed after Cleanup()")
	}
}

// --- GenerateSessionName edge cases ---

func TestGenerateSessionName_Unicode(t *testing.T) {
	got := GenerateSessionName("セッション名")
	// "セッション名" は6ルーン、全て非ASCII文字なので全て _ に置換
	want := "______"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "セッション名", got, want)
	}
}

func TestGenerateSessionName_MixedUnicode(t *testing.T) {
	got := GenerateSessionName("my-セッション-01")
	// "セッション" は5ルーン → "_____"
	want := "my-_____-01"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "my-セッション-01", got, want)
	}
}

func TestGenerateSessionName_LongName(t *testing.T) {
	input := strings.Repeat("a", 1000)
	got := GenerateSessionName(input)
	if len(got) != 1000 {
		t.Errorf("GenerateSessionName with 1000 char input: len = %d, want 1000", len(got))
	}
	if got != input {
		t.Errorf("GenerateSessionName should preserve valid long names")
	}
}

func TestGenerateSessionName_Underscores(t *testing.T) {
	// '_' は [^a-zA-Z0-9-] なので '_' に変換されるが結果は同じ
	got := GenerateSessionName("my_session_01")
	want := "my_session_01"
	if got != want {
		t.Errorf("GenerateSessionName(%q) = %q, want %q", "my_session_01", got, want)
	}
}

// --- New edge cases ---

func TestNew_SessionWithSpaces_Sanitized(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "hello world",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if w.session != "hello_world" {
		t.Errorf("session = %q, want %q", w.session, "hello_world")
	}
}

func TestNew_BothNilControllerAndPaneManager(t *testing.T) {
	_, err := New(Config{
		Session:  "test",
		ShimuxPath: "/bin/echo",
	})
	if err == nil {
		t.Fatal("New() with nil Controller and PaneManager should return error")
	}
	// Controller はPaneManagerより先にチェックされる
	if !strings.Contains(err.Error(), "controller is required") {
		t.Errorf("error = %q, want to contain 'controller is required'", err.Error())
	}
}

// --- Run edge cases ---

func TestRun_SetsEnvironmentVariables(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "env-test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	// env コマンドで環境変数を出力して確認
	err = w.Run(context.Background(), []string{"sh", "-c", "test \"$SHIMUX\" = 1 && test \"$SHIMUX_SESSION\" = env-test"})
	if err != nil {
		t.Fatalf("Run() should set SHIMUX=1 and SHIMUX_SESSION=env-test, error = %v", err)
	}
}

func TestRun_PATHIncludesTmpDir(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "path-test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	// which tmux が symlink を見つけることを確認
	err = w.Run(context.Background(), []string{"sh", "-c", "which tmux | grep -q shimux-wrapper"})
	if err != nil {
		t.Fatalf("Run() should prepend tmpDir to PATH making tmux resolvable, error = %v", err)
	}
}

func TestRun_TMUXPaneEnvSet(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "pane-env-test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"sh", "-c", "test \"$TMUX_PANE\" = '%0' && test \"$SHIMUX_PANE_ID\" = '0'"})
	if err != nil {
		t.Fatalf("Run() should set TMUX_PANE=%%0 and SHIMUX_PANE_ID=0, error = %v", err)
	}
}

func TestRun_NonExistentCommand_Error(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"/nonexistent/command"})
	if err == nil {
		t.Fatal("Run() with non-existent command should return error")
	}
}

func TestRun_CleanupAfterError(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	// false コマンドはエラーを返すが cleanup は実行される
	_ = w.Run(context.Background(), []string{"false"})

	// tmpDir が cleanup されていることを確認
	if w.tmpDir != "" {
		if _, err := os.Stat(w.tmpDir); !os.IsNotExist(err) {
			t.Error("tmpDir should be cleaned up even after command error")
		}
	}
}

func TestRun_MultipleArgs(t *testing.T) {
	ctrl := &ghosttytest.MockController{}
	pm := pane.NewManager(filepath.Join(t.TempDir(), "panes.json"))
	w, err := New(Config{
		Controller:  ctrl,
		PaneManager: pm,
		Session:     "test",
		ShimuxPath:    "/bin/echo",
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = w.Run(context.Background(), []string{"echo", "arg1", "arg2", "arg3"})
	if err != nil {
		t.Fatalf("Run() with multiple args should succeed, error = %v", err)
	}
}
